site_name: filamentWallet Docs
theme:
  name: readthedocs
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  tabs: true

nav:
  - Installation: index.md
  - Currencies: currency.md
  - Transfer Methods: transfer_method.md
  #  - Deposit Methods: d_m.md
  #  - Withdrawal Methods: w_m.md
  - Currency Exchange Rates: currency_exchange.md
  - FAQ: faq.md
  - Changelog: changelog.md
