site_name: phpWallet Docs
theme: 
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  tabs: true

nav:
  - Installation: index.md
  - Currencies: currency.md
  - Deposit Methods: d_m.md
  - Withdrawal Methods: w_m.md
  - Currency Exchange Rates: e_r.mdr
  - FAQ: faq.md
  - Changelog: changelog.md
